Repository exasim-project/NeoN, pull requests merged in 2024-05, with the labels that each got.

#50 fix: neofoam compiles with cuda support and gcc
  .gitignore
  CHANGELOG.md
  CMakePresets.json
  cmake/CxxThirdParty.cmake
Labels: ready-for-review

#57 change case
  CHANGELOG.md
  applications/solver/minimal/setRootCase.H
  benchmarks/fields/bench_fields.cpp
  include/NeoFOAM/core/Error.hpp
  include/NeoFOAM/core/Time.hpp
  include/NeoFOAM/core/executor/CPUExecutor.hpp
  include/NeoFOAM/core/executor/GPUExecutor.hpp
  include/NeoFOAM/core/executor/OMPExecutor.hpp
  include/NeoFOAM/core/executor/executor.hpp
  include/NeoFOAM/fields/Field.hpp
  include/NeoFOAM/helpers/exceptions.hpp
  src/core/Error.cpp
  src/core/Kokkos.cpp
  test/test_Executor.cpp
  test/test_Field.cpp
Labels: ready-for-review, ready-to-merge

#52 Feat/dictionary
  CHANGELOG.md
  doc/basics/dictionary.rst
  doc/basics/index.rst
  doc/index.rst
  include/NeoFOAM/core/Dictionary.hpp
  src/CMakeLists.txt
  src/core/Dictionary.cpp
  test/CMakeLists.txt
  test/test_Dictionary.cpp
  test/test_main.cpp
Labels: ready-to-merge

#58 Feat/workflow
  .github/workflows/build.yaml
  .github/workflows/build_doc.yaml
  .gitignore
  .reuse/dep5
  .vscode/settings.json
  .vscode/tasks.json
  CHANGELOG.md
  CMakeLists.txt
  CMakePresets.json
  benchmarks/CMakeLists.txt
  cmake/Docs.cmake
  doc/Doxyfile.in
  doc/_static/installation/cmakePresets.gif
  doc/contributing.rst
  doc/installation.rst
  test/CMakeLists.txt
Labels: ready-for-review, ready-to-merge

#60 Refactor CI/CD implementation
  .github/workflows/build_on_aws.yml
  .github/workflows/check_changelog.yaml
  .github/workflows/clang-tidy-check.yml
  .github/workflows/format-check.yml
  .github/workflows/header_check.yaml
  .github/workflows/static_checks.yaml
  .github/workflows/typo_check.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  CMakePresets.json
Labels: ready-for-review, full-ci

#53 Feat/unstructured mesh
  CHANGELOG.md
  doc/Doxyfile.in
  doc/basics/containers.rst
  doc/basics/executor.rst
  doc/basics/index.rst
  doc/basics/unstructuredMesh.rst
  doc/fvcc/DSL.rst
  doc/fvcc/boundaryConditions.rst
  doc/fvcc/index.rst
  doc/fvcc/operators.rst
  doc/fvcc/stencil.rst
  doc/index.rst
  doc/installation.rst
  include/NeoFOAM/fields/FieldTypeDefs.hpp
  include/NeoFOAM/mesh/stencil/StencilDataBase.hpp
  include/NeoFOAM/mesh/unstructuredMesh/BoundaryMesh.hpp
  include/NeoFOAM/mesh/unstructuredMesh/UnstructuredMesh.hpp
  include/NeoFOAM/primitives/label.hpp
  src/CMakeLists.txt
  src/mesh/stencil/StencilDataBase.cpp
  src/mesh/unstructuredMesh/BoundaryMesh.cpp
  src/mesh/unstructuredMesh/UnstructuredMesh.cpp
Labels: documentation, enhancement, ready-for-review
