Repository exasim-project/NeoN, pull requests merged in 2024-09, with the labels that each got.

#139 disable span from tempory objects and simplification related to fields
  CHANGELOG.md
  cmake/AutoEnableDevice.cmake
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/fields/operations/comparison.hpp
  include/NeoFOAM/fields/operations/operationsMacros.hpp
  test/catch2/test_main.cpp
  test/core/parallelAlgorithms.cpp
  test/fields/field.cpp
Labels: ready-for-review, discussion

#134 improved error handling and addition of tokenList and Input
  CHANGELOG.md
  include/NeoFOAM/core/demangle.hpp
  include/NeoFOAM/core/dictionary.hpp
  include/NeoFOAM/core/inputs.hpp
  include/NeoFOAM/core/tokenList.hpp
  src/CMakeLists.txt
  src/core/demangle.cpp
  src/core/dictionary.cpp
  src/core/tokenList.cpp
  test/core/CMakeLists.txt
  test/core/dictionary.cpp
  test/core/inputs.cpp
  test/core/tokenList.cpp
Labels: ready-for-review, ready-to-merge

#132 Cache build folder
  .github/workflows/build.yaml
  .github/workflows/build_on_aws.yml
  .github/workflows/static_checks.yaml
  include/NeoFOAM/fields/field.hpp
Labels: ready-for-review, full-ci, Skip-Changelog

#128 Fix the order of in/out parameters
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/linear.hpp
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/surfaceInterpolation.hpp
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/upwind.hpp
  src/finiteVolume/cellCentred/interpolation/linear.cpp
  src/finiteVolume/cellCentred/interpolation/upwind.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenGrad.cpp
  test/finiteVolume/CMakeLists.txt
  test/finiteVolume/cellCentred/interpolation/CMakeLists.txt
  test/finiteVolume/cellCentred/interpolation/linear.cpp
Labels: ready-for-review, Skip-Changelog

#146 fix compiler warnings
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surfaceBoundaryFactory.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenDiv.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenGrad.hpp
  include/NeoFOAM/finiteVolume/cellCentred/stencil/geometryScheme.hpp
  src/core/tokenList.cpp
  src/finiteVolume/cellCentred/interpolation/linear.cpp
  src/finiteVolume/cellCentred/interpolation/upwind.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenGrad.cpp
  src/finiteVolume/cellCentred/stencil/basicGeometryScheme.cpp
  test/core/parallelAlgorithms.cpp
Labels: ready-for-review, Skip-Changelog
