Repository exasim-project/NeoN, pull requests merged in 2024-12, with the labels that each got.

#155 Feat/database
  .github/workflows/build_doc.yaml
  doc/basics/database.rst
  doc/basics/index.rst
  doc/finiteVolume/cellCentred/index.rst
  include/NeoFOAM/core/database/collection.hpp
  include/NeoFOAM/core/database/database.hpp
  include/NeoFOAM/core/database/document.hpp
  include/NeoFOAM/core/database/fieldCollection.hpp
  include/NeoFOAM/core/database/oldTimeCollection.hpp
  include/NeoFOAM/fields/domainField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/geometricField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/surfaceField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/volumeField.hpp
  src/CMakeLists.txt
  src/core/database/collection.cpp
  src/core/database/database.cpp
  src/core/database/document.cpp
  src/core/database/fieldCollection.cpp
  src/core/database/oldTimeCollection.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenGrad.cpp
  src/finiteVolume/cellCentred/stencil/geometryScheme.cpp
  test/core/CMakeLists.txt
  test/core/database/CMakeLists.txt
  test/core/database/collection.cpp
  test/core/database/customTestCollection.hpp
  test/core/database/database.cpp
  test/core/database/document.cpp
  test/core/database/fieldCollection.cpp
  test/core/database/oldTimeCollection.cpp
  test/dsl/expression.cpp
  test/dsl/operator.cpp
  test/dsl/timeIntegration/timeIntegration.cpp
  test/fields/field.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
  test/finiteVolume/cellCentred/interpolation/linear.cpp
Labels: documentation, enhancement, ready-for-review

#185 Implement document based database
  .github/workflows/build_doc.yaml
  .github/workflows/build_on_aws.yml
  CHANGELOG.md
  cmake/AutoEnableDevice.cmake
  doc/basics/database.rst
  doc/basics/index.rst
  doc/finiteVolume/cellCentred/index.rst
  include/NeoFOAM/core/database/collection.hpp
  include/NeoFOAM/core/database/database.hpp
  include/NeoFOAM/core/database/document.hpp
  include/NeoFOAM/core/database/fieldCollection.hpp
  include/NeoFOAM/core/database/oldTimeCollection.hpp
  include/NeoFOAM/fields/domainField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/geometricField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/surfaceField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/volumeField.hpp
  src/CMakeLists.txt
  src/core/database/collection.cpp
  src/core/database/database.cpp
  src/core/database/document.cpp
  src/core/database/fieldCollection.cpp
  src/core/database/oldTimeCollection.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenGrad.cpp
  src/finiteVolume/cellCentred/stencil/geometryScheme.cpp
  test/core/CMakeLists.txt
  test/core/database/CMakeLists.txt
  test/core/database/collection.cpp
  test/core/database/customTestCollection.hpp
  test/core/database/database.cpp
  test/core/database/document.cpp
  test/core/database/fieldCollection.cpp
  test/core/database/oldTimeCollection.cpp
  test/dsl/expression.cpp
  test/dsl/operator.cpp
  test/dsl/timeIntegration/timeIntegration.cpp
  test/fields/field.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
  test/finiteVolume/cellCentred/interpolation/linear.cpp
Labels: full-ci

#188 Fix shadowing warnings
  .github/workflows/build_on_aws.yml
  cmake/AutoEnableDevice.cmake
  cmake/CxxThirdParty.cmake
  include/NeoFOAM/core/database/oldTimeCollection.hpp
  test/fields/field.cpp
Labels: full-ci

#186 fix unstructured mesh test by copying to host before assert
  README.md
  cmake/AutoEnableDevice.cmake
  include/NeoFOAM/core/database/collection.hpp
  src/mesh/unstructured/unstructuredMesh.cpp
  test/core/database/fieldCollection.cpp
  test/mesh/unstructured/unstructuredMesh.cpp
Labels: ready-for-review, full-ci, Skip-Changelog

#191 add fixme workflow
  .github/workflows/static_checks.yaml
  test/finiteVolume/cellCentred/operator/divOperator.cpp
Labels: Skip-Changelog, Skip-build

#211 build adapter with alternative branch if possible
  .github/workflows/build_adapter.yaml
  test/finiteVolume/cellCentred/operator/divOperator.cpp
Labels: Skip-Changelog

#81 add time integration methods based on sundials
  .github/workflows/build_adapter.yaml
  .vscode/settings.json
  CHANGELOG.md
  CMakeLists.txt
  cmake/CxxThirdParty.cmake
  doc/index.rst
  doc/timeIntegration/forwardEuler.rst
  doc/timeIntegration/index.rst
  doc/timeIntegration/rungeKutta.rst
  include/NeoFOAM/core/database/database.hpp
  include/NeoFOAM/core/database/fieldCollection.hpp
  include/NeoFOAM/core/executor/CPUExecutor.hpp
  include/NeoFOAM/core/executor/GPUExecutor.hpp
  include/NeoFOAM/core/executor/executor.hpp
  include/NeoFOAM/core/executor/serialExecutor.hpp
  include/NeoFOAM/core/runtimeSelectionFactory.hpp
  include/NeoFOAM/dsl/expression.hpp
  include/NeoFOAM/dsl/operator.hpp
  include/NeoFOAM/dsl/solver.hpp
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/geometricField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/surfaceField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/volumeField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/surfaceInterpolation.hpp
  include/NeoFOAM/timeIntegration/forwardEuler.hpp
  include/NeoFOAM/timeIntegration/rungeKutta.hpp
  include/NeoFOAM/timeIntegration/sundials.hpp
  include/NeoFOAM/timeIntegration/timeIntegration.hpp
  src/CMakeLists.txt
  src/finiteVolume/cellCentred/interpolation/linear.cpp
  src/finiteVolume/cellCentred/interpolation/upwind.cpp
  src/timeIntegration/rungeKutta.cpp
  src/timeIntegration/timeIntegration.cpp
  test/CMakeLists.txt
  test/core/database/fieldCollection.cpp
  test/core/database/oldTimeCollection.cpp
  test/core/parallelAlgorithms.cpp
  test/dsl/CMakeLists.txt
  test/dsl/coeff.cpp
  test/dsl/expression.cpp
  test/dsl/operator.cpp
  test/fields/domainField.cpp
  test/fields/field.cpp
  test/finiteVolume/cellCentred/boundary/surface/surfFixedValue.cpp
  test/finiteVolume/cellCentred/boundary/volume/volFixedGradient.cpp
  test/finiteVolume/cellCentred/boundary/volume/volFixedValue.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
  test/finiteVolume/cellCentred/interpolation/linear.cpp
  test/finiteVolume/cellCentred/interpolation/surfaceInterpolation.cpp
  test/finiteVolume/cellCentred/operator/divOperator.cpp
  test/mesh/unstructured/unstructuredMesh.cpp
  test/timeIntegration/CMakeLists.txt
  test/timeIntegration/forwardEuler.cpp
  test/timeIntegration/rungeKutta.cpp
  test/timeIntegration/timeIntegration.cpp
Labels: enhancement, ready-for-review, full-ci

#214 add macos workflow
  .github/workflows/build_on_macos.yaml
  .github/workflows/build_on_ubuntu.yaml
Labels: ready-for-review, ci

#215 add sanitizer workflows
  .github/workflows/build_with_san.yaml
  REUSE.toml
  include/NeoFOAM/core/database/fieldCollection.hpp
  scripts/san_ignores.txt
  src/timeIntegration/rungeKutta.cpp
  test/core/database/fieldCollection.cpp
  test/core/database/oldTimeCollection.cpp
  test/timeIntegration/rungeKutta.cpp
  test/timeIntegration/timeIntegration.cpp
Labels: full-ci, ci

#157 Add windows build workflow
  .github/workflows/build_on_aws.yaml
  .github/workflows/build_on_windows.yaml
  .gitignore
  AUTHORS.md
  CHANGELOG.md
  CMakeLists.txt
  CMakePresets.json
  README.md
  benchmarks/fields/CMakeLists.txt
  cmake/AutoEnableDevice.cmake
  cmake/CxxThirdParty.cmake
  cmake/Docs.cmake
  doc/installation.rst
  include/NeoFOAM/core/demangle.hpp
  include/NeoFOAM/core/runtimeSelectionFactory.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary.hpp
  include/NeoFOAM/timeIntegration/sundials.hpp
  src/CMakeLists.txt
  src/core/demangle.cpp
  src/finiteVolume/cellCentred/boundary/boundary.cpp
  test/CMakeLists.txt
  test/core/CMakeLists.txt
  test/core/database/fieldCollection.cpp
  test/core/database/oldTimeCollection.cpp
  test/fields/field.cpp
  test/finiteVolume/cellCentred/boundary/surface/surfFixedValue.cpp
  test/finiteVolume/cellCentred/boundary/volume/volFixedGradient.cpp
  test/finiteVolume/cellCentred/boundary/volume/volFixedValue.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
  test/finiteVolume/cellCentred/interpolation/linear.cpp
  test/finiteVolume/cellCentred/interpolation/surfaceInterpolation.cpp
  test/finiteVolume/cellCentred/operator/divOperator.cpp
  test/timeIntegration/CMakeLists.txt
  test/timeIntegration/rungeKutta.cpp
  test/timeIntegration/timeIntegration.cpp
Labels: full-ci

#218 Refactor includes
  .github/workflows/build_on_aws.yaml
  include/NeoFOAM/NeoFOAM.hpp
  include/NeoFOAM/core.hpp
  include/NeoFOAM/core/database/fieldCollection.hpp
  include/NeoFOAM/core/database/oldTimeCollection.hpp
  include/NeoFOAM/core/runtimeSelectionFactory.hpp
  include/NeoFOAM/dsl.hpp
  include/NeoFOAM/dsl/ddt.hpp
  include/NeoFOAM/dsl/explicit.hpp
  include/NeoFOAM/dsl/operator.hpp
  include/NeoFOAM/fields.hpp
  include/NeoFOAM/fields/operations/sum.hpp
  include/NeoFOAM/finiteVolume/cellCentred.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/boundary.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/empty.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/geometricField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/linear.hpp
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/surfaceInterpolation.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/divOperator.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenGrad.hpp
  include/NeoFOAM/finiteVolume/cellCentred/stencil/basicGeometryScheme.hpp
  include/NeoFOAM/finiteVolume/cellCentred/stencil/geometryScheme.hpp
  include/NeoFOAM/timeIntegration.hpp
  include/NeoFOAM/timeIntegration/sundials.hpp
  src/core/database/database.cpp
  src/executor/CPUExecutor.cpp
  src/finiteVolume/cellCentred/interpolation/upwind.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/stencil/geometryScheme.cpp
  test/core/database/collection.cpp
  test/core/database/customTestCollection.hpp
  test/core/database/database.cpp
  test/core/database/document.cpp
  test/core/database/fieldCollection.cpp
  test/core/database/oldTimeCollection.cpp
  test/dsl/common.hpp
  test/dsl/expression.cpp
  test/fields/field.cpp
  test/finiteVolume/cellCentred/boundary/surface/surfFixedValue.cpp
  test/finiteVolume/cellCentred/boundary/volume/volFixedGradient.cpp
  test/finiteVolume/cellCentred/boundary/volume/volFixedValue.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
  test/finiteVolume/cellCentred/interpolation/linear.cpp
  test/finiteVolume/cellCentred/interpolation/surfaceInterpolation.cpp
  test/finiteVolume/cellCentred/operator/divOperator.cpp
  test/mesh/unstructured/communicator.cpp
  test/timeIntegration/forwardEuler.cpp
  test/timeIntegration/rungeKutta.cpp
  test/timeIntegration/timeIntegration.cpp
Labels: full-ci

#217 - Added, the much requested, NF_PING() feature.
  doc/basics/macros.rst
  include/NeoFOAM/core/info.hpp
Labels: ready-for-review, Skip-Changelog
