Repository exasim-project/NeoN, pull requests merged in 2024-10, with the labels that each got.

#145 Add fields from existing memory and internal fields
  include/NeoFOAM/fields/boundaryFields.hpp
  include/NeoFOAM/fields/domainField.hpp
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/surfaceField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/volumeField.hpp
Labels: Skip-Changelog

#151 Implementation of operator coefficient handler
  include/NeoFOAM/DSL/coeff.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenDiv.hpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/timeIntegration/forwardEuler.cpp
  test/dsl/CMakeLists.txt
  test/dsl/coeff.cpp
  test/dsl/dsl.cpp
  test/fields/field.cpp
Labels: ready-for-review, Skip-Changelog, dsl

#156 Add flag to switch mpi support on/off
  CMakeLists.txt
  cmake/CxxThirdParty.cmake
  include/NeoFOAM/core/error.hpp
  include/NeoFOAM/core/mpi/environment.hpp
  include/NeoFOAM/core/mpi/fullDuplexCommBuffer.hpp
  include/NeoFOAM/core/mpi/halfDuplexCommBuffer.hpp
  include/NeoFOAM/core/mpi/operators.hpp
  include/NeoFOAM/mesh/unstructured/communicator.hpp
  src/CMakeLists.txt
  test/catch2/CMakeLists.txt
  test/core/CMakeLists.txt
  test/core/mpi/CMakeLists.txt
  test/mesh/unstructured/CMakeLists.txt
Labels: ready-to-merge

#150 Implementation of DSL Equations
  include/NeoFOAM/DSL/equation.hpp
  include/NeoFOAM/DSL/operator.hpp
  include/NeoFOAM/finiteVolume/cellCentred/timeIntegration/forwardEuler.hpp
  include/NeoFOAM/finiteVolume/cellCentred/timeIntegration/timeIntegration.hpp
  src/finiteVolume/cellCentred/timeIntegration/forwardEuler.cpp
  test/dsl/CMakeLists.txt
  test/dsl/common.hpp
  test/dsl/dsl.cpp
  test/dsl/equation.cpp
  test/dsl/operator.cpp
  test/finiteVolume/cellCentred/timeIntegration/timeIntegration.cpp
Labels: ready-for-review, Skip-Changelog, dsl

#160 Add templated unit test for runTimeSelectionFactory
  .github/workflows/build_doc.yaml
  doc/requirements.txt
  test/core/CMakeLists.txt
  test/core/registerClass.cpp
  test/core/runTimeSelectionFactory.cpp
Labels: ready-for-review, Skip-Changelog

#165 Fix adapter build workflow
  .github/workflows/build_adapter.yaml
  .github/workflows/of_pubkey.gpg
Labels: Skip-Changelog

#166 Use setup-openfoam action
  .github/workflows/build_adapter.yaml
  AUTHORS.md
Labels: Skip-Changelog

#167 Ci/setup of
  .github/workflows/build_adapter.yaml
  AUTHORS.md
Labels: Skip-Changelog

#158 Implementation of basic time integration
  include/NeoFOAM/dsl/coeff.hpp
  include/NeoFOAM/dsl/ddt.hpp
  include/NeoFOAM/dsl/expression.hpp
  include/NeoFOAM/dsl/operator.hpp
  include/NeoFOAM/dsl/solver.hpp
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/geometricField.hpp
  include/NeoFOAM/timeIntegration/forwardEuler.hpp
  include/NeoFOAM/timeIntegration/timeIntegration.hpp
  test/CMakeLists.txt
  test/dsl/CMakeLists.txt
  test/dsl/coeff.cpp
  test/dsl/common.hpp
  test/dsl/expression.cpp
  test/dsl/operator.cpp
  test/dsl/timeIntegration/CMakeLists.txt
  test/dsl/timeIntegration/timeIntegration.cpp
  test/finiteVolume/CMakeLists.txt
  test/finiteVolume/cellCentred/timeIntegration/timeIntegration.cpp
Labels: Skip-Changelog, dsl

#173 Remove old dsl
  doc/basics/fields.rst
  doc/dsl/equation.rst
  doc/dsl/index.rst
  doc/dsl/operator.rst
  doc/finiteVolume/cellCentred/index.rst
  doc/index.rst
  include/NeoFOAM/DSL/coeff.hpp
  include/NeoFOAM/DSL/equation.hpp
  include/NeoFOAM/DSL/operator.hpp
  include/NeoFOAM/finiteVolume/cellCentred/timeIntegration/forwardEuler.hpp
  include/NeoFOAM/finiteVolume/cellCentred/timeIntegration/timeIntegration.hpp
  src/CMakeLists.txt
  src/finiteVolume/cellCentred/timeIntegration/forwardEuler.cpp
  test/dsl/CMakeLists.txt
  test/dsl/equation.cpp
Labels: ready-for-review, ready-to-merge, Skip-Changelog

#168 Develop function for constructing 1D Mesh
  AUTHORS.md
  include/NeoFOAM/mesh/unstructured/boundaryMesh.hpp
  include/NeoFOAM/mesh/unstructured/unstructuredMesh.hpp
  src/mesh/unstructured/unstructuredMesh.cpp
  test/mesh/unstructured/unstructuredMesh.cpp
Labels: enhancement, Skip-Changelog
