Repository exasim-project/NeoN, pull requests merged in 2024-07, with the labels that each got.

#92 Field from std::vector constructor and subrange access
  benchmarks/fields/bench_fields.cpp
  include/NeoFOAM/core/executor/CPUExecutor.hpp
  include/NeoFOAM/core/executor/GPUExecutor.hpp
  include/NeoFOAM/core/executor/OMPExecutor.hpp
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/fields/operations/comparison.hpp
  include/NeoFOAM/fields/operations/operationsMacros.hpp
  src/mesh/unstructured/boundaryMesh.cpp
  test/fields/CMakeLists.txt
  test/fields/field.cpp
Labels: enhancement, ready-for-review

#79 78 mpi infrastructure
  .clang-format
  .github/workflows/build.yaml
  .github/workflows/static_checks.yaml
  .vscode/c_cpp_properties.json
  CHANGELOG.md
  CMakeLists.txt
  cmake/CxxThirdParty.cmake
  doc/basics/mpi_architecture.rst
  include/NeoFOAM/core/error.hpp
  include/NeoFOAM/core/mpi/environment.hpp
  include/NeoFOAM/core/mpi/fullDuplexCommBuffer.hpp
  include/NeoFOAM/core/mpi/halfDuplexCommBuffer.hpp
  include/NeoFOAM/core/mpi/operators.hpp
  include/NeoFOAM/core/primitives/vector.hpp
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/mesh/unstructured/communicator.hpp
  src/CMakeLists.txt
  src/core/mpi/halfDuplexCommBuffer.cpp
  src/mesh/unstructured/communicator.cpp
  test/CMakeLists.txt
  test/core/CMakeLists.txt
  test/core/mpi/CMakeLists.txt
  test/core/mpi/test_fullDuplexCommBuffer.cpp
  test/core/mpi/test_halfDuplexCommBuffer.cpp
  test/fields/CMakeLists.txt
  test/mesh/CMakeLists.txt
  test/mesh/unstructured/CMakeLists.txt
  test/mesh/unstructured/test_communicator.cpp
  test/test_main.cpp
Labels: enhancement, ready-for-review, ready-to-merge

#107 FIX: surface and VolumeField domain internalField size was incorrect
  include/NeoFOAM/finiteVolume/cellCentred/fields/geometricField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/surfaceField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/volumeField.hpp
Labels: ready-for-review

#108 improvements to vector and dictionary
  CHANGELOG.md
  include/NeoFOAM/core/dictionary.hpp
  include/NeoFOAM/core/primitives/vector.hpp
  include/NeoFOAM/core/time.hpp
  include/NeoFOAM/fields/operations/sum.hpp
  src/CMakeLists.txt
  src/core/dictionary.cpp
  src/core/primitives/vector.cpp
  src/core/time.cpp
  test/core/dictionary.cpp
  test/fields/field.cpp
Labels: ready-for-review

#105 87 minor mpi corrections
  CHANGELOG.md
  CMakeLists.txt
  include/NeoFOAM/core/mpi/environment.hpp
  include/NeoFOAM/core/mpi/operators.hpp
  include/NeoFOAM/core/primitives/vector.hpp
  src/CMakeLists.txt
  src/core/mpi/halfDuplexCommBuffer.cpp
  test/core/mpi/CMakeLists.txt
  test/core/mpi/operators.cpp
Labels: ready-for-review, ready-to-merge

#110 Simplify boundary condition implementation
  include/NeoFOAM/core/executor/OMPExecutor.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surface/calculated.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surface/empty.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surface/fixedValue.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surfaceBoundaryFactory.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/calculated.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/empty.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/fixedGradient.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/fixedValue.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volumeBoundaryFactory.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/surfaceField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/volumeField.hpp
  include/NeoFOAM/mesh/stencil/fvccGeometryScheme.hpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
Labels: ready-for-review

#114 Debug/aws
  .github/workflows/build_on_aws.yml
  include/NeoFOAM/core/error.hpp
  test/CMakeLists.txt
  test/mesh/unstructured/communicator.cpp
Labels: full-ci

#112 Simplify cmake presets
  .github/workflows/build.yaml
  .github/workflows/build_on_aws.yml
  .github/workflows/static_checks.yaml
  AUTHORS.md
  CMakeLists.txt
  CMakePresets.json
  README.md
  benchmarks/CMakeLists.txt
  cmake/AutoEnableDevice.cmake
  cmake/CPM.cmake
  cmake/CompilerWarnings.cmake
  cmake/CxxThirdParty.cmake
  doc/installation.rst
  include/CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/catch2/CMakeLists.txt
Labels: full-ci, Skip-Changelog

#117 Fix CMake benchmark targets
  README.md
  benchmarks/CMakeLists.txt
  benchmarks/fields/CMakeLists.txt
  scripts/plotBenchmarks.py
  test/CMakeLists.txt
Labels: Skip-Changelog

#113 Fix compiler warnings
  benchmarks/fields/bench_fields.cpp
  doc/basics/containers.rst
  doc/finiteVolume/cellCentred/boundaryConditions.rst
  include/NeoFOAM/core/mpi/environment.hpp
  include/NeoFOAM/core/mpi/fullDuplexCommBuffer.hpp
  include/NeoFOAM/core/mpi/halfDuplexCommBuffer.hpp
  include/NeoFOAM/core/mpi/operators.hpp
  include/NeoFOAM/core/parallelAlgorithms.hpp
  include/NeoFOAM/core/primitives/label.hpp
  include/NeoFOAM/core/primitives/vector.hpp
  include/NeoFOAM/core/time.hpp
  include/NeoFOAM/fields/boundaryFields.hpp
  include/NeoFOAM/fields/domainField.hpp
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/fields/operations/comparison.hpp
  include/NeoFOAM/fields/operations/operationsMacros.hpp
  include/NeoFOAM/fields/operations/sum.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/boundaryPatchMixin.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surfaceBoundaryFactory.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/empty.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/fixedGradient.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volumeBoundaryFactory.hpp
  include/NeoFOAM/mesh/unstructured/communicator.hpp
  include/NeoFOAM/mesh/unstructured/unstructuredMesh.hpp
  src/core/mpi/halfDuplexCommBuffer.cpp
  src/mesh/unstructured/boundaryMesh.cpp
  src/mesh/unstructured/communicator.cpp
  src/mesh/unstructured/unstructuredMesh.cpp
  test/catch2/mpiReporter.cpp
  test/catch2/mpiSerialization.cpp
  test/core/mpi/fullDuplexCommBuffer.cpp
  test/core/mpi/halfDuplexCommBuffer.cpp
  test/core/mpi/operators.cpp
  test/core/parallelAlgorithms.cpp
  test/fields/field.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
  test/mesh/unstructured/communicator.cpp
Labels: full-ci, Skip-Changelog

#120 Relax openmp requirement
  CHANGELOG.md
  CMakePresets.json
  benchmarks/fields/bench_fields.cpp
  cmake/AutoEnableDevice.cmake
  doc/api/executor.rst
  doc/basics/containers.rst
  doc/basics/executor.rst
  doc/basics/mpi_architecture.rst
  include/NeoFOAM/core/executor/CPUExecutor.hpp
  include/NeoFOAM/core/executor/executor.hpp
  include/NeoFOAM/core/executor/serialExecutor.hpp
  include/NeoFOAM/core/parallelAlgorithms.hpp
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/fields/operations/sum.hpp
  src/CMakeLists.txt
  src/executor/CPUExecutor.cpp
  src/executor/OMPExecutor.cpp
  src/executor/serialExecutor.cpp
  test/core/executor.cpp
  test/core/parallelAlgorithms.cpp
  test/fields/domainField.cpp
  test/fields/field.cpp
  test/finiteVolume/cellCentred/boundary/surface/surfFixedValue.cpp
  test/finiteVolume/cellCentred/boundary/volume/volFixedGradient.cpp
  test/finiteVolume/cellCentred/boundary/volume/volFixedValue.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
  test/mesh/unstructured/communicator.cpp
  test/mesh/unstructured/unstructuredMesh.cpp
Labels: full-ci

#73 Add a style guide section
  .github/workflows/static_checks.yaml
  doc/contributing.rst
Labels: Skip-Changelog

#116 Remove reuse deprecation warning
  .pre-commit-config.yaml
  .reuse/dep5
  REUSE.toml
Labels: Skip-Changelog

#100 Operators and interpolation implementation.
  CHANGELOG.md
  include/NeoFOAM/core/primitives/scalar.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surface/calculated.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surface/empty.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surface/fixedValue.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surfaceBoundaryFactory.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/calculated.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/empty.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/fixedGradient.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/fixedValue.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volumeBoundaryFactory.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/surfaceField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/fields/volumeField.hpp
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/linear.hpp
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/surfaceInterpolation.hpp
  include/NeoFOAM/finiteVolume/cellCentred/interpolation/upwind.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenDiv.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenGrad.hpp
  include/NeoFOAM/finiteVolume/cellCentred/stencil/basicGeometryScheme.hpp
  include/NeoFOAM/finiteVolume/cellCentred/stencil/geometryScheme.hpp
  include/NeoFOAM/finiteVolume/cellCentred/stencil/stencilDataBase.hpp
  include/NeoFOAM/mesh/unstructured/unstructuredMesh.hpp
  src/CMakeLists.txt
  src/finiteVolume/cellCentred/boundary/boundary.cpp
  src/finiteVolume/cellCentred/interpolation/linear.cpp
  src/finiteVolume/cellCentred/interpolation/upwind.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenGrad.cpp
  src/finiteVolume/cellCentred/stencil/basicGeometryScheme.cpp
  src/finiteVolume/cellCentred/stencil/geometryScheme.cpp
  src/finiteVolume/cellCentred/stencil/stencilDataBase.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
Labels: full-ci

#119 Add a build_apdater workflow
  .github/workflows/build_adapter.yaml
Labels: Skip-Changelog

#125 Doc/fix doxygen build
  .github/workflows/build.yaml
  .github/workflows/build_adapter.yaml
  .github/workflows/build_doc.yaml
  .github/workflows/static_checks.yaml
  doc/contributing.rst
Labels: Skip-Changelog, Skip-build

#129 Improve documentation
  AUTHORS.md
  doc/api/executor.rst
  doc/api/fields.rst
  doc/api/index.rst
  doc/basics/containers.rst
  doc/basics/executor.rst
  doc/basics/fields.rst
  doc/basics/index.rst
  doc/basics/macros.rst
  doc/basics/mpi_architecture.rst
  doc/basics/registerclass.rst
  doc/basics/unstructuredMesh.rst
  doc/contributing.rst
  doc/finiteVolume/cellCentred/boundaryConditions.rst
  doc/finiteVolume/cellCentred/fields.rst
  doc/index.rst
  include/NeoFOAM/finiteVolume/cellCentred/boundary/surfaceBoundaryFactory.hpp
Labels: Skip-Changelog, Skip-build
