Repository exasim-project/NeoN, pull requests merged in 2025-03, with the labels that each got.

#187 benchmarking and platform codesign
  include/NeoFOAM/core/parallelAlgorithms.hpp
  include/NeoFOAM/finiteVolume/cellCentred/boundary/volume/fixedGradient.hpp
  src/finiteVolume/cellCentred/interpolation/upwind.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
Labels: enhancement, ready-for-review, ready-to-merge, full-ci

#278 add basic span implementation
  include/NeoFOAM/core.hpp
  include/NeoFOAM/core/span.hpp
  test/core/CMakeLists.txt
  test/core/span.cpp
Labels: ready-for-review, full-ci

#277 Courant number implementation
  CHANGELOG.md
  include/NeoFOAM/finiteVolume/cellCentred.hpp
  include/NeoFOAM/finiteVolume/cellCentred/auxiliary/coNum.hpp
  src/CMakeLists.txt
  src/finiteVolume/cellCentred/auxiliary/coNum.cpp
  test/finiteVolume/CMakeLists.txt
  test/finiteVolume/cellCentred/auxiliary/CMakeLists.txt
  test/finiteVolume/cellCentred/auxiliary/coNum.cpp
Labels: full-ci

#270 disable copying of field collection
  include/NeoFOAM/core/database/collection.hpp
  include/NeoFOAM/core/database/database.hpp
  include/NeoFOAM/core/database/fieldCollection.hpp
  src/core/database/collection.cpp
  src/core/database/database.cpp
  test/core/database/fieldCollection.cpp
Labels: ready-for-review, ready-to-merge, Skip-Changelog

#272 Ginkgo config solver
  CHANGELOG.md
  cmake/CxxThirdParty.cmake
  include/NeoFOAM/core/dictionary.hpp
  include/NeoFOAM/core/error.hpp
  include/NeoFOAM/core/primitives/scalar.hpp
  include/NeoFOAM/core/primitives/vector.hpp
  include/NeoFOAM/dsl/ddt.hpp
  include/NeoFOAM/dsl/solver.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/expression.hpp
  include/NeoFOAM/linearAlgebra/ginkgo.hpp
  include/NeoFOAM/linearAlgebra/utilities.hpp
  include/NeoFOAM/timeIntegration/backwardEuler.hpp
  src/CMakeLists.txt
  src/linearAlgebra/ginkgo.cpp
  test/CMakeLists.txt
  test/finiteVolume/cellCentred/operator/ddtOperator.cpp
  test/finiteVolume/cellCentred/operator/sourceTerm.cpp
  test/linearAlgebra/CMakeLists.txt
  test/linearAlgebra/ginkgo.cpp
  test/linearAlgebra/linearAlgebra.cpp
  test/linearAlgebra/linearSystem.cpp
Labels: full-ci

#251 Add executor generator for tests and benchmarks
  benchmarks/CMakeLists.txt
  benchmarks/fields/field.cpp
  benchmarks/finiteVolume/cellCentred/operator/divOperator.cpp
  test/CMakeLists.txt
  test/catch2/executorGenerator.hpp
  test/mesh/unstructured/unstructuredMesh.cpp
Labels: ready-for-review, full-ci

#282 281 view
  include/NeoFOAM/finiteVolume/cellCentred/operators/ddtOperator.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/expression.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenDiv.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenLaplacian.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/sourceTerm.hpp
  include/NeoFOAM/linearAlgebra/CSRMatrix.hpp
  include/NeoFOAM/linearAlgebra/linearSystem.hpp
  src/finiteVolume/cellCentred/operators/sourceTerm.cpp
  test/linearAlgebra/CSRMatrix.cpp
  test/linearAlgebra/linearSystem.cpp
Labels: ready-for-review, Skip-Changelog

#280 Thirdparty configuration for ADIOS2
  CMakeLists.txt
  cmake/CxxThirdParty.cmake
  cmake/patches/adios2_kokkos.patch
Labels: build

#285 Improve Field access safety.
  CHANGELOG.md
  doc/basics/fields.rst
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/timeIntegration/sundials.hpp
  src/finiteVolume/cellCentred/pressureVelocityCoupling/pressureVelocityCoupling.cpp
  src/mesh/unstructured/unstructuredMesh.cpp
  test/core/database/fieldCollection.cpp
  test/core/database/oldTimeCollection.cpp
  test/core/parallelAlgorithms.cpp
  test/dsl/coeff.cpp
  test/dsl/common.hpp
  test/dsl/spatialOperator.cpp
  test/dsl/temporalOperator.cpp
  test/fields/field.cpp
  test/fields/segmentedField.cpp
  test/finiteVolume/cellCentred/fields/surfaceField.cpp
  test/finiteVolume/cellCentred/fields/volumeField.cpp
  test/finiteVolume/cellCentred/interpolation/linear.cpp
  test/finiteVolume/cellCentred/interpolation/upwind.cpp
  test/finiteVolume/cellCentred/operator/ddtOperator.cpp
  test/finiteVolume/cellCentred/operator/gaussGreenDiv.cpp
  test/finiteVolume/cellCentred/operator/laplacianOperator.cpp
  test/finiteVolume/cellCentred/operator/sourceTerm.cpp
  test/linearAlgebra/CSRMatrix.cpp
  test/linearAlgebra/linearSystem.cpp
  test/mesh/unstructured/unstructuredMesh.cpp
  test/timeIntegration/rungeKutta.cpp
Labels: ready-for-review, full-ci
