Repository exasim-project/NeoN, pull requests merged in 2025-09, with the labels that each got.

#340 Add destructor to ddtOperator, SourceTerm, and SparsityPattern
  include/NeoN/finiteVolume/cellCentred/operators/ddtOperator.hpp
  include/NeoN/finiteVolume/cellCentred/operators/sourceTerm.hpp
  include/NeoN/linearAlgebra/sparsityPattern.hpp
  src/finiteVolume/cellCentred/operators/ddtOperator.cpp
  src/finiteVolume/cellCentred/operators/sourceTerm.cpp
Labels: ready-for-review

#238 Add an option to apply pre-commit and clang-tidy fixes
  .github/workflows/build_doc.yaml
  .github/workflows/static_checks.yaml
  .gitignore
  doc/contributing.rst
Labels: build, auto-fix

#351 Stop mirrroing the repo to GitLab.com
  .github/workflows/gitlab-mirror.yml
Labels: ready-for-review, Skip-Changelog, ci

#356 Trigger GitLab CI from GitHub
  .github/workflows/gitlab-ci.yaml
  .github/workflows/mirror.yaml
  .gitlab-ci.yml
Labels: Skip-Changelog, Skip-build, ci

#368 Fix Ginkgo config solver issue.
  include/NeoN/linearAlgebra/ginkgo.hpp
  src/linearAlgebra/ginkgo.cpp
Labels: ready-for-review
