Repository exasim-project/NeoN, pull requests merged in 2025-01, with the labels that each got.

#223 handle Kokkos reducers in parallelReduce
  AUTHORS.md
  include/NeoFOAM/core/parallelAlgorithms.hpp
  test/core/parallelAlgorithms.cpp
Labels: enhancement

#221 Update documentation
  .github/workflows/build_doc.yaml
  .github/workflows/build_on_windows.yaml
  CMakePresets.json
  README.md
  benchmarks/fields/bench_fields.cpp
  doc/_static/custom.css
  doc/basics/algorithms.rst
  doc/basics/containers.rst
  doc/basics/executor.rst
  doc/basics/fields.rst
  doc/basics/freeFunctions/fill.rst
  doc/basics/freeFunctions/map.rst
  doc/basics/freeFunctions/setField.rst
  doc/basics/index.rst
  doc/basics/macros.rst
  doc/basics/registerclass.rst
  doc/basics/unstructuredMesh.rst
  doc/conf.py
  doc/contributing.rst
  doc/datastructures/database.rst
  doc/datastructures/dictionary.rst
  doc/datastructures/index.rst
  doc/datastructures/unstructuredMesh.rst
  doc/dsl/index.rst
  doc/dsl/operator.rst
  doc/finiteVolume/cellCentred/boundaryConditions.rst
  doc/finiteVolume/cellCentred/case_study.rst
  doc/finiteVolume/cellCentred/index.rst
  doc/index.rst
  doc/installation.rst
  doc/mpi_architecture.rst
  include/NeoFOAM/core/executor/executor.hpp
  include/NeoFOAM/fields.hpp
  include/NeoFOAM/fields/field.hpp
  include/NeoFOAM/fields/fieldFreeFunctions.hpp
  include/NeoFOAM/fields/operations/comparison.hpp
  include/NeoFOAM/fields/operations/operationsMacros.hpp
  include/NeoFOAM/finiteVolume/cellCentred/operators/gaussGreenDiv.hpp
  test/fields/domainField.cpp
Labels: full-ci, Skip-Changelog

#233 make Kokkos_ENABLE_SERIAL a default
  cmake/AutoEnableDevice.cmake
Labels: ready-for-review, build

#225 - added std::exit back into `NF_ERROR_EXIT`.
  include/NeoFOAM/core/error.hpp
Labels: bug, ready-for-review, Skip-Changelog

#219 Adds a minimal implementation linear algebra functionality
  CHANGELOG.md
  include/NeoFOAM/linearAlgebra/CSRMatrix.hpp
  include/NeoFOAM/linearAlgebra/LinearSystem.hpp
  test/CMakeLists.txt
  test/linearAlgebra/CMakeLists.txt
  test/linearAlgebra/linearSystem.cpp
Labels: documentation, enhancement

#236 FIX: infinite loop in parallel scan on windows
  CHANGELOG.md
  include/NeoFOAM/fields/segmentedField.hpp
  include/NeoFOAM/linearAlgebra.hpp
  include/NeoFOAM/linearAlgebra/CSRMatrix.hpp
  include/NeoFOAM/linearAlgebra/linearSystem.hpp
  test/CMakeLists.txt
  test/core/parallelAlgorithms.cpp
  test/linearAlgebra/CMakeLists.txt
  test/linearAlgebra/linearSystem.cpp
Labels: bug, full-ci

#202 ENH: add segmentedField to represent vector of vectors
  CHANGELOG.md
  doc/basics/index.rst
  doc/basics/segmentedField.rst
  include/NeoFOAM/core/parallelAlgorithms.hpp
  include/NeoFOAM/fields/segmentedField.hpp
  test/core/parallelAlgorithms.cpp
  test/fields/CMakeLists.txt
  test/fields/segmentedField.cpp
Labels: enhancement, ready-for-review, full-ci

#241 Execute benchmarks on aws
  .github/workflows/build_on_aws.yaml
  CMakeLists.txt
  CMakePresets.json
  benchmarks/CMakeLists.txt
  benchmarks/catch_main.hpp
  benchmarks/fields/CMakeLists.txt
  benchmarks/fields/bench_fields.cpp
  benchmarks/fields/field.cpp
  benchmarks/finiteVolume/cellCentred/operator/CMakeLists.txt
  benchmarks/finiteVolume/cellCentred/operator/divOperator.cpp
  scripts/catch2json.py
  scripts/plotBenchmarks.py
Labels: ready-for-review, full-ci, build

#244 Add comparison run to benchmark workflow
  .github/workflows/build_on_aws.yaml
Labels: ready-for-review, full-ci, build
