Repository exasim-project/NeoN, pull requests merged in 2025-04, with the labels that each got.

#292 290 linear algebra rename
  .vscode/settings.json
  include/NeoFOAM/finiteVolume/cellCentred/linearAlgebra/sparsityPattern.hpp
  include/NeoFOAM/linearAlgebra/CSRMatrix.hpp
  include/NeoFOAM/linearAlgebra/linearSystem.hpp
  include/NeoFOAM/linearAlgebra/utilities.hpp
  src/finiteVolume/cellCentred/operators/ddtOperator.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/operators/sourceTerm.cpp
  src/finiteVolume/cellCentred/pressureVelocityCoupling/pressureVelocityCoupling.cpp
  test/finiteVolume/cellCentred/linearAlgebra/sparsityPattern.cpp
  test/linearAlgebra/CSRMatrix.cpp
  test/linearAlgebra/linearSystem.cpp
Labels: ready-for-review, Skip-Changelog

#275 Fix/cmake target prefix
  CMakeLists.txt
  include/CMakeLists.txt
  test/CMakeLists.txt
  test/catch2/CMakeLists.txt
  test/core/mpi/CMakeLists.txt
  test/mesh/unstructured/CMakeLists.txt
Labels: ready-to-merge

#305 FIX: colIdx got copied instread of referenced
  include/NeoN/finiteVolume/cellCentred/dsl/expression.hpp
  include/NeoN/linearAlgebra/CSRMatrix.hpp
Labels: bug

#311 views free function
  CHANGELOG.md
  doc/basics/algorithms.rst
  doc/basics/segmentedField.rst
  doc/mpi_architecture.rst
  include/NeoN/core/mpi/fullDuplexCommBuffer.hpp
  include/NeoN/core/mpi/halfDuplexCommBuffer.hpp
  include/NeoN/core/view.hpp
  include/NeoN/dsl/coeff.hpp
  include/NeoN/dsl/solver.hpp
  include/NeoN/dsl/spatialOperator.hpp
  include/NeoN/fields/fieldFreeFunctions.hpp
  include/NeoN/fields/segmentedVector.hpp
  include/NeoN/finiteVolume/cellCentred/boundary/volume/extrapolated.hpp
  include/NeoN/finiteVolume/cellCentred/boundary/volume/fixedGradient.hpp
  include/NeoN/finiteVolume/cellCentred/boundary/volume/fixedValue.hpp
  include/NeoN/finiteVolume/cellCentred/dsl/expression.hpp
  include/NeoN/finiteVolume/cellCentred/linearAlgebra/sparsityPattern.hpp
  include/NeoN/linearAlgebra/CSRMatrix.hpp
  include/NeoN/linearAlgebra/linearSystem.hpp
  include/NeoN/linearAlgebra/petscSolverContext.hpp
  src/dsl/coeff.cpp
  src/finiteVolume/cellCentred/auxiliary/coNum.cpp
  src/finiteVolume/cellCentred/faceNormalGradient/uncorrected.cpp
  src/finiteVolume/cellCentred/interpolation/linear.cpp
  src/finiteVolume/cellCentred/interpolation/upwind.cpp
  src/finiteVolume/cellCentred/linearAlgebra/sparsityPattern.cpp
  src/finiteVolume/cellCentred/operators/ddtOperator.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenDiv.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenGrad.cpp
  src/finiteVolume/cellCentred/operators/gaussGreenLaplacian.cpp
  src/finiteVolume/cellCentred/operators/sourceTerm.cpp
  src/finiteVolume/cellCentred/stencil/basicGeometryScheme.cpp
  src/finiteVolume/cellCentred/stencil/cellToFaceStencil.cpp
  src/mesh/unstructured/boundaryMesh.cpp
  src/mesh/unstructured/unstructuredMesh.cpp
  test/core/view.cpp
  test/dsl/coeff.cpp
  test/dsl/common.hpp
  test/fields/segmentedVector.cpp
  test/fields/vector.cpp
  test/finiteVolume/cellCentred/linearAlgebra/sparsityPattern.cpp
  test/linearAlgebra/CSRMatrix.cpp
  test/linearAlgebra/ginkgo.cpp
  test/linearAlgebra/linearSystem.cpp
  test/linearAlgebra/petsc.cpp
Labels: ready-for-review, ready-to-merge

#310 FIX: cuda compiler identified dsl::exp namespace as exp function
  test/dsl/coeff.cpp
Labels: bug, ready-for-review, ready-to-merge

#316 refactor residual computation
  include/NeoN/dsl/expression.hpp
  include/NeoN/finiteVolume/cellCentred/boundary.hpp
  include/NeoN/finiteVolume/cellCentred/dsl/expression.hpp
  include/NeoN/linearAlgebra/ginkgo.hpp
  include/NeoN/linearAlgebra/linearSystem.hpp
  include/NeoN/linearAlgebra/utilities.hpp
  src/linearAlgebra/ginkgo.cpp
  src/linearAlgebra/utilities.cpp
  test/core/view.cpp
  test/dsl/common.hpp
  test/linearAlgebra/CMakeLists.txt
  test/linearAlgebra/linearSystem.cpp
  test/linearAlgebra/utilities.cpp
Labels: ready-for-review
